entrada = input('Digite algo: ')
print('O valor digitado é {}'.format(type(entrada)))
print('O valor digitado é um número? ', entrada.isnumeric())
print('O valor digitado é um texto? ', entrada.isalpha())
print('O valor digitado é alphanumerico? ', entrada.isalnum())
print('O valor digitado é um decimal? ', entrada.isdecimal())
print('O valor digitado está em maiúsculo?', entrada.isupper())
print('O valor digitado está em minúsculo? ', entrada.islower())
print('O valor digitado é imprimivél? ', entrada.isprintable())
print('O valor digitado é um espaço? ', entrada.isspace())
