nome = str(input('Digite um nome: ').strip().upper())
#n = nome.split()
#print('Seu primeiro nome é {}'.format(n[0]))
#print(len(n))
#print('Seu último nome é {}'.format(n[len(n)-1]))
#print(nome.find('A')+1)
#print(nome.rfind('A')+1)